#!/bin/sh

printf "new title: "
read -r TITLE

FILEDATE="$(date +%m%d%y-%H%M%S)"
DATE="Date: $(date +%d/%m/%y) - $(date +%H:%M:%S)"
FILE="blog/I/$FILEDATE.lh"
printf "%s\n\n" "$TITLE" > "$FILE"
printf "%s\n" "$DATE" >> "$FILE"

echo "$FILE"

${EDITOR:-vi} "$FILE"
